### ISSUE TITLE
Missing nop between lh/lui (ASPSX v2.21)

### ISSUE THREAD

**Issue by shao113** [mkst/maspsx#87]
https://decomp.me/scratch/ssfgq

maspsx omits a nop at 1cc:
![maspsx-missing-nop](https://github.com/user-attachments/assets/48ad9e67-ff4a-432a-aa5d-48f05a9cf960)

**Comment by mkst** [comment]
Thanks for raising the bug, it should now be fixed - see https://decomp.me/scratch/NRtsT.

**Comment by shao113** [comment]
Thanks!

I think this issue extends to registers besides v0 as well. I'm seeing it locally with v1 and a2 for example, and with s0 in this scratch at a3c: https://decomp.me/scratch/z8hns

**Comment by mkst** [comment]
This should also be fixed on `master` now (I'll get it deployed to decomp.me shortly). Out of interest, what game/library are you working on? There's not been a lot of testing against ASPSX 2.21 so you are providing valuable help by identifying these deficiencies in maspsx - thank you :)

**Comment by shao113** [comment]
Vandal Hearts, presumably PsyQ 3.4. And glad I can help! maspsx will vastly simplify my builds as well.

Found a couple variations still missing the nop:
https://decomp.me/scratch/uiu32
https://decomp.me/scratch/REDMb (4a0)
Note the second one may be less reliable since it doesn't work with psyq-obj-parser as-is (Unknown relocation type 30)
